# Generated by Django 5.1.5 on 2025-01-15 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0004_remove_supplier_name_supplier_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
    ]
