
services:
  # Web service
  web:
    build: .
    command: ["sh", "-c", "/migratescript.sh"]
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - app_network

  # Database service (PostgreSQL)
  db:
    image: postgres:13
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app_network

  # Celery worker service
  celery:
    build: .
    command: celery -A inventory worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - app_network

  # Celery beat service
  celery_beat:
    build: .
    command: celery -A inventory beat --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
